/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.


declare module '@granite-js/react-native' {
  interface RegisterScreenInput {

  }

  interface RegisterScreen {

  }
}
